# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('title2', models.CharField(blank=True, max_length=200, null=True)),
                ('title3', models.CharField(blank=True, max_length=200, null=True)),
                ('title4', models.CharField(blank=True, max_length=200, null=True)),
                ('text1', models.TextField(blank=True, null=True)),
                ('text2', models.TextField(blank=True, null=True)),
                ('text3', models.TextField(blank=True, null=True)),
                ('text4', models.TextField(blank=True, null=True)),
                ('text5', models.TextField(blank=True, null=True)),
                ('image1', models.FileField(blank=True, null=True, upload_to=b'')),
                ('image2', models.FileField(blank=True, null=True, upload_to=b'')),
                ('image3', models.FileField(blank=True, null=True, upload_to=b'')),
                ('image4', models.FileField(blank=True, null=True, upload_to=b'')),
                ('image5', models.FileField(blank=True, null=True, upload_to=b'')),
                ('image6', models.FileField(blank=True, null=True, upload_to=b'')),
                ('image7', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('title2', models.CharField(blank=True, max_length=500)),
                ('title3', models.CharField(blank=True, max_length=500)),
                ('title4', models.CharField(blank=True, max_length=500)),
                ('text', models.TextField(blank=True, null=True)),
                ('text2', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_text', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=b'')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('base_url', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('lan_menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('prof', models.CharField(blank=True, max_length=500)),
                ('info', models.TextField()),
                ('image', models.FileField(upload_to=b'')),
                ('slug', models.SlugField(blank=True, max_length=40)),
                ('Language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('slider_image', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('title2', models.CharField(blank=True, max_length=250, null=True)),
                ('title3', models.CharField(blank=True, max_length=250, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('data2', models.TextField(blank=True, null=True)),
                ('data3', models.TextField(blank=True, null=True)),
                ('image1', models.FileField(blank=True, null=True, upload_to=b'')),
                ('image2', models.FileField(blank=True, null=True, upload_to=b'')),
                ('image3', models.FileField(blank=True, null=True, upload_to=b'')),
                ('image4', models.FileField(blank=True, null=True, upload_to=b'')),
                ('image5', models.FileField(blank=True, null=True, upload_to=b'')),
                ('image6', models.FileField(blank=True, null=True, upload_to=b'')),
                ('image7', models.FileField(blank=True, null=True, upload_to=b'')),
                ('lan_submenu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Language')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Menu')),
            ],
        ),
        migrations.AddField(
            model_name='context',
            name='context_lan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Language'),
        ),
        migrations.AddField(
            model_name='context',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Menu'),
        ),
        migrations.AddField(
            model_name='context',
            name='submenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.SubMenu'),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='article_lan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Language'),
        ),
    ]
