# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='language_name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='language_name_ka',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='language_name_ru',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
