# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20160705_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='data_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='data_ka',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='data_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='name_ka',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='slug_en',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='slug_ka',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='slug_ru',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
