# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20160705_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecontext',
            name='article_lan',
        ),
        migrations.RemoveField(
            model_name='context',
            name='context_lan',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='lan_menu',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='Language',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='lan_submenu',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
