# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20160705_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecontext',
            name='text1_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='text1_ka',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='text1_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='text2_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='text2_ka',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='text2_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='text3_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='text3_ka',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='text3_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='text4_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='text4_ka',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='text4_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='text5_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='text5_ka',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='text5_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='title2_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='title2_ka',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='title2_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='title3_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='title3_ka',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='title3_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='title4_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='title4_ka',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='title4_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='title_ka',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='text2_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='text2_ka',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='text2_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='text_ka',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='title2_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='title2_ka',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='title2_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='title3_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='title3_ka',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='title3_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='title4_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='title4_ka',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='title4_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='title_ka',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='title_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='info_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='info_ka',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='info_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='name_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='name_ka',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='name_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='prof_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='prof_ka',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='prof_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='slider_text_en',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='slider_text_ka',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='slider_text_ru',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='data2_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='data2_ka',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='data2_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='data3_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='data3_ka',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='data3_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='data_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='data_ka',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='data_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='slug_en',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='slug_ka',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='slug_ru',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='title2_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='title2_ka',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='title2_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='title3_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='title3_ka',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='title3_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='title_ka',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='title_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
